# Generated by Django 5.2.7 on 2025-11-27 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlertSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_threshold', models.IntegerField(default=3, verbose_name='Alert threshold, in %')),
                ('alarm_threshold', models.IntegerField(default=5, verbose_name='Alarm threshold, in %')),
                ('alert_hyst', models.IntegerField(default=1, verbose_name='Alert hysteresis, in %, to avoid alert/recovery cycles')),
                ('time_interval_check', models.IntegerField(default=10, verbose_name='Time interval check for the portfolio price variation, in min')),
                ('time_interval_update', models.IntegerField(default=60, verbose_name='Time interval to update the IB portfolio with the bot, in min')),
            ],
        ),
        migrations.CreateModel(
            name='API',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ReportSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calculate_pattern', models.BooleanField(default=True)),
                ('calculate_trend', models.BooleanField(default=True)),
                ('daily_report_period', models.IntegerField(default=3, verbose_name='Period in years in the past downloaded for the reports')),
            ],
        ),
        migrations.CreateModel(
            name='SchedulerSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pf_check', models.BooleanField(default=True)),
                ('index_check', models.BooleanField(default=True)),
                ('report', models.BooleanField(default=True)),
                ('intraday', models.BooleanField(default=False)),
                ('heartbeat', models.BooleanField(default=False)),
                ('heartbeat_ib', models.BooleanField(default=True)),
                ('update_slow_strat', models.BooleanField(default=True)),
                ('time_interval_interday', models.IntegerField(default=60, verbose_name='Time interval for intraday trading, how often should the report runs')),
                ('opening_check_minute_shift', models.IntegerField(default=5, verbose_name='Opening check minute shift, how many minutes after opening should the alerting starts')),
                ('daily_report_minute_shift', models.IntegerField(default=5, verbose_name='Daily report minute shift, how many minutes before closing should the report be generated')),
            ],
        ),
        migrations.CreateModel(
            name='OrderSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perform_order', models.BooleanField(default=True)),
                ('default_api_alerting', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='default_api_alerting', to='general_settings.api')),
                ('default_api_orders', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='default_api_orders', to='general_settings.api')),
                ('default_api_reporting', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='default_api_reporting', to='general_settings.api')),
            ],
        ),
    ]
